resources:
  - kafka_ingest-deployment.yaml
  - python_stream_processor-deployment.yaml
  - spark_batch_processor-deployment.yaml
  - realtime_processor-deployment.yaml
  - ksqdb_connector-deployment.yaml
  - serving_trino-deployment.yaml
  - visualization_superset-deployment.yaml
  - visualization_metabase-deployment.yaml
  - data_catalog-deployment.yaml
  - airflow-deployment.yaml
  - prometheus.yaml
  - grafana.yaml
