apiVersion: apps/v1
kind: Deployment
metadata:
  name: serving-trino
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serving-trino
  template:
    metadata:
      labels:
        app: serving-trino
    spec:
      containers:
      - name: serving-trino
        image: "{{ SERVING_TRINO_IMAGE }}"
