apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ingest
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-stream-processor
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-batch-processor
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: realtime-processor
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ksqdb-connector
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: serving-trino
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: visualization-superset
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: visualization-metabase
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-catalog
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow
spec:
  replicas: 2
