apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: data-pipeline-app
spec:
  project: default
  source:
    repoURL: "{{ REPO_URL }}"
    targetRevision: HEAD
    path: "infra/k8s/overlays/dev"
  destination:
    server: "{{ K8S_API_SERVER }}"
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
