name: Build, Push & Update Deployments

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and tag Docker images for each service using the commit SHA as version
      - name: Build Kafka Ingest Image
        run: |
          cd services/kafka_ingest
          docker build -t ${{ secrets.DOCKER_USERNAME }}/kafka_ingest:${{ github.sha }} .
      - name: Build Python Stream Processor Image
        run: |
          cd services/python_stream_processor
          docker build -t ${{ secrets.DOCKER_USERNAME }}/python_stream_processor:${{ github.sha }} .
      - name: Build Spark Batch Processor Image
        run: |
          cd services/spark_batch_processor
          docker build -t ${{ secrets.DOCKER_USERNAME }}/spark_batch_processor:${{ github.sha }} .
      - name: Build Realtime Processor Image
        run: |
          cd services/realtime_processor
          docker build -t ${{ secrets.DOCKER_USERNAME }}/realtime_processor:${{ github.sha }} .
      - name: Build ksqDB Connector Image
        run: |
          cd services/ksqdb_connector
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ksqdb_connector:${{ github.sha }} .
      - name: Build Trino Serving Image
        run: |
          cd services/serving_trino
          docker build -t ${{ secrets.DOCKER_USERNAME }}/serving_trino:${{ github.sha }} .
      - name: Build Superset Image
        run: |
          cd services/visualization_superset
          docker build -t ${{ secrets.DOCKER_USERNAME }}/visualization_superset:${{ github.sha }} .
      - name: Build Metabase Image
        run: |
          cd services/visualization_metabase
          docker build -t ${{ secrets.DOCKER_USERNAME }}/visualization_metabase:${{ github.sha }} .
      - name: Build Data Catalog Image
        run: |
          cd services/data_catalog
          docker build -t ${{ secrets.DOCKER_USERNAME }}/data_catalog:${{ github.sha }} .

      - name: Push All Images
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/kafka_ingest:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/python_stream_processor:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/spark_batch_processor:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/realtime_processor:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/ksqdb_connector:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/serving_trino:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/visualization_superset:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/visualization_metabase:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/data_catalog:${{ github.sha }}

      # Update image tags in Kustomize base file with the new version (commit SHA)
      - name: Update Kustomize Manifests
        run: |
          # Replace "latest" with the current commit SHA in the base kustomization.yaml
          sed -i "s/newTag: \"latest\"/newTag: \"${{ github.sha }}\"/g" infra/k8s/base/kustomization.yaml
          # Commit and push changes (skip if no changes are detected)
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add infra/k8s/base/kustomization.yaml
          git commit -m "Update image tags to ${{ github.sha }}" || echo "No manifest updates"
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Notify Deployment Update
        run: |
          echo "Deployment manifests updated with new image tags. ArgoCD or your Kubernetes pipeline will pick up the changes."
